name: The Life Strategic
favicon: null
layout_spectrum: 0.20576
typography_spectrum: 0.88428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#402828'
    - '#f7f5f8'
    - '#cfcddb'
    - '#917a6c'
    - '#8c4f30'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
