name: The Life Strategic
favicon: null
layout_spectrum: 0.8908904492855072
typography_spectrum: 0.7778317220509052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#402828'
    - '#f7f5f8'
    - '#cfcddb'
    - '#917a6c'
    - '#8c4f30'
  brandStrength: 0.28149560489691794
  lightness: 0.5533476446289569
  saturation: 0.8828727214131504
  rhythmicContrast: 0.5
purpose: []
